### PR TITLE
WIP: Use ninja to build

### PR DESCRIPTION
**Pull request by jakirkham**
Trying to use [`ninja`]( https://ninja-build.org/ ) for building to see if that may help us speed up this build.

### CODE REVIEW

**Comment by jakirkham** [comment]
Encountered a test failure on CircleCI. See snippet below.

```
356/380 Test #748: pyinstallcheck_KrigingRandomVector_std .................................***Failed    0.50 sec
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/work/openturns-1.7/python/test/t_KrigingRandomVector_std.py", line 58, in <module>
    assert_almost_equal(covariancePoint, theoricalVariance, 7e-7, 7e-7)
RuntimeError: Value 7.35e-07 is not close enough to 0
--- /feedstock_root/build_artefacts/work/openturns-1.7/python/test/t_KrigingRandomVector_std.expout	2016-01-27 10:44:54.000000000 +0000
+++ /feedstock_root/build_artefacts/work/openturns-1.7/build/python/test/t_KrigingRandomVector_std.out	2016-06-28 00:50:16.482967235 +0000
@@ -1,12 +0,0 @@
-Realization of the KRV= [-0.249]
-Sample of realizations of the KRV=     [ marginal 1 ]
-0 : [ -0.244     ]
-1 : [ -0.26      ]
-2 : [ -0.254     ]
-3 : [ -0.254     ]
-4 : [ -0.246     ]
-5 : [ -0.239     ]
-6 : [ -0.246     ]
-7 : [ -0.249     ]
-8 : [ -0.243     ]
-9 : [ -0.243     ]
```

**Comment by jschueller** [comment]
@jakirkham, this is quite fast! Would it allow to build for 2.7,3.4 & 3.5 on circleci ? Isn't the limit 2h ?
I've already cotired openturns to get even faster builds, this is how the 3 linux builds passed.

**Comment by jakirkham** [comment]
Well, this change is already applied to CircleCI so that should give you some idea of how long this build takes there. Though you should be able to combine this with `cotire`. Not sure how that affects the performance, but it is certainly worth an experiment don't you think? 😉

**Comment by jakirkham** [comment]
It is true that CircleCI has a 2hr limit. We should try to figure out how to get a proper build matrix on CircleCI so that we are not so time restricted.

**Comment by jschueller** [comment]
Seems build matrix is not supported on circleci.

**Comment by jschueller** [comment]
The failure you reported is fixed in openturns.

**Comment by jschueller** [comment]
Why increment the build number ? It shouldn't change the content of the package for end-users, only add osx.

**Comment by jakirkham** [comment]
> Seems build matrix is not supported on circleci.

Yeah, not directly, but they do have something they call [parallelism]( https://circleci.com/docs/setting-up-parallelism/ ). Also, there is this [code]( https://github.com/michaelcontento/circleci-matrix ) that uses parallelism to give something like a build matrix, which we might be able to incorporate into [`conda-smithy`]( https://github.com/conda-forge/conda-smithy ). Just something to think about.

**Comment by jakirkham** [comment]
> Why increment the build number ? It shouldn't change the content of the package for end-users, only add osx.

I figured since we have changed how the build is being done the number should be bumped. Though I don't have strong feelings on it if you think otherwise.

**Comment by jakirkham** [comment]
> The failure you reported is fixed in openturns.

Do we need to add a patch for the fix?

**Comment by jschueller** [comment]
No need to patch, next version should be released soon.

**Comment by jschueller** [comment]
I also tested ninja, no miracles here, it just parallelizes jobs by default, I got similar results by using make -j2...

**Comment by jakirkham** [comment]
Sorry forgot to drop the WIP.

**Comment by jschueller** [comment]
Thanks!

**Pull request merged**
