### PR TITLE
WIP: Try to build for Mac

### PR DESCRIPTION
**Pull request by jakirkham**
Currently, this does not work as we are running into build time limits on Travis CI.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @jschueller

**Comment by jschueller** [comment]
@jakirkham, I'm investigating unity builds to speed up mac worker for the next version of openturns.
I succeeded in building in 5 minutes instead of 30 with 1 core, but it won't be ready until next version.

**Comment by jakirkham** [comment]
Again thinking of writing Travis CI and asking them for more build time. However, we are already drafting a different request right now so it probably won't be done right away.

Still this seems to build even though it is right up against the limit. Should we maybe just put it in and then retrigger builds that go over?

**Comment by jschueller** [comment]
@jakirkham, I don't think this is an option as the next openturns version will get bigger
I have to investigate unity builds or else enable -j2 on osx to make it build reliably, but I know how you feel for option 2 :)

**Comment by jakirkham** [comment]
> I don't think this is an option as the next openturns version will get bigger

Couldn't we deal with the next version when it comes out and accept this for now?

> I have to investigate unity builds

👍

> ...or else enable -j2 on osx to make it build reliably, but I know how you feel for option 2 :)

Hmm...yeah...while it seems to work on Travis CI, my experience with not following guidelines on number of cores provided by any webservice has generally been frustrating. I would rather save you that fate.

**Comment by jschueller** [comment]
@jakirkham, next openturns version 1.8rc1 is due this month, I'll try to get unity builds working

**Pull request closed without merging**
