### PR TITLE
Rebuild with parallel OpenBLAS

### PR DESCRIPTION
**Pull request by jakirkham**
Bump build number and rebuild with the parallel OpenBLAS.

### CODE REVIEW

**Comment by jakirkham** [comment]
Looks like this relies on `hmat-oss` being rebuilt for it to pass. Please see PR ( https://github.com/conda-forge/hmat-oss-feedstock/pull/1 ) for that rebuild.

**Comment by jakirkham** [comment]
Looks like this relies on `hmat-oss` being rebuilt for it to pass. Please see PR ( https://github.com/conda-forge/hmat-oss-feedstock/pull/1 ) for that rebuild.

**Comment by jschueller** [comment]
@jakirkham could you resubmit the travis build after the hmat-oss bump ?

**Comment by jakirkham** [comment]
Restarted the CIs now that `hmat-oss` is deployed.

**Comment by jakirkham** [comment]
This is now passing. Please take it in when you are ready.

**Comment by jakirkham** [comment]
Sorry, I had forgotten to take the WIP off earlier.

**Pull request merged**
