### PR TITLE
Use m2w64

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
hi @mingwandroid, I'm trying to compile using m2w64, and I've got undefined references to python symbols linking my python modules, I guess the native ```libs/pythonXY.lib``` is a static lib, which lib do I have to link to ?

**Comment by mingwandroid** [comment]
`conda install libpython`

**Comment by jschueller** [comment]
@mingwandroid thanks!

**Comment by jschueller** [comment]
@mingwandroid I dont see it ever used in conda-forge ??

**Comment by mingwandroid** [comment]
Probably because no one on conda-forge has tried this yet? I've done it a good few times on defaults.

**Comment by jschueller** [comment]
@mingwandroid I'd need a m2w64-muparser package, how can I proceed ?

**Comment by mingwandroid** [comment]
Hmm, you may want to just make a package for this, using `m2w64-toolchain` prefixing it to `Library/mingw-w64`.

**Comment by jschueller** [comment]
in conda-forge ?

**Comment by mingwandroid** [comment]
Yeah, sure, why not. Eventually I hope to move all m2-* to conda-forge and also build them from source.

**Comment by jschueller** [comment]
hi @mingwandroid, it works fine for win64 builds! but it fails at the import for the win32 version. Did I miss something in my recipe ? I am sure libpython is the right version ?

**Comment by mingwandroid** [comment]
Likely 32 bit requires stack alignment is the python interface module. Add VERBOSE=1 to the make execution please so we get useful logs. I hate default non verbose logs.. as useful as a chocolate teapot.

**Comment by jschueller** [comment]
ok, I enable VERBOSE=1, do I have to add a specific flag ?

**Comment by jschueller** [comment]
Here is a compilation line for the lib:
```
[  2%] Building CXX object lib/src/CMakeFiles/OT.dir/Base/Algo/FittingAlgorithmImplementation.cxx.obj
cd /d C:\bld\openturns_1501689675587\work\openturns-1.9\build\lib\src && C:\bld\openturns_1501689675587\_b_env\Library\mingw-w64\bin\g++.exe  -DHAVE_CONFIG_H -DOT_DLL_EXPORTS -DOT_EXPORTS @CMakeFiles/OT.dir/includes_CXX.rsp -O2 -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4   -o CMakeFiles\OT.dir\Base\Algo\FittingAlgorithmImplementation.cxx.obj -c C:\bld\openturns_1501689675587\work\openturns-1.9\lib\src\Base\Algo\FittingAlgorithmImplementation.cxx
```

**Comment by mingwandroid** [comment]
You need -mstackrealign for the single object that contains the every point from Python and only for 32 bit Windows.

Doing it in any other object would slow them down unnecessarily.

**Comment by jschueller** [comment]
You mean entry point? I use swig so I guess all my swig modules would need to be compiled with -mstackrealign. Why did I not need it until then as we also provided our own mingw builds ?

**Comment by mingwandroid** [comment]
Your own mingwpy based builds or msys2/mingw-w64 builds (using Python can with GCC) or ..?

**Comment by jschueller** [comment]
mingw-w64 from archlinux

**Comment by mingwandroid** [comment]
I've not checked for a while but I guess Arch uses our msys2 patches for python to build it with GCC? If so then there'd be no need to realign.

The stack realignment is done to work around the fact that mingw-w64 assumes 16 byte stack alignment but msvc only provides 8 but stack alignment (on 32 bit).

Therefore interface functions where msvc calls mingw-w64 need prologues to ensure 16 byte alignment.

Note, I am not 100% sure this is what you've run into, to figure that out you'd need to use gdb.

**Comment by jschueller** [comment]
no, we compiled our module against native python libs like here too, maybe it's a parameter of the toochain ?

**Comment by mingwandroid** [comment]
Maybe they compile their toolchain to do that all the time? It is horrible to do that though .. OK, well, I'd just try adding it to CFLAGS and CXXFLAGS and see if it fixes your problem. Here'a a recipe where I use so something similar: https://github.com/conda/conda-recipes/blob/master/xgboost/build.sh

**Comment by jschueller** [comment]
ok I'll try that first

**Comment by jschueller** [comment]
mmmh, adding -mstackrealign to CXXFLAGS doesnt make it work

**Comment by jschueller** [comment]
@mingwandroid there seem to be a problem related to exceptions is there something I should know regarding exceptions with m2w64 ?

(at loading our cxx lib tries to load config files and if they dont exsit an exception is thrown and catched)

**Comment by mingwandroid** [comment]
Yes, exceptions on 32-bit mingw-w64 use sjlj and are not compatible with MS's SEH exceptions. I think you would need to rework this exceptional code path to not use exceptions.

**Comment by jschueller** [comment]
archlinux mingw-w64 toolchain also uses sjlj and exceptions work fine there

That would not be possible to avoid exceptions for openturns.

**Comment by mingwandroid** [comment]
Ok I'll need to look into this then but I've got no time to do that at present. Can you ignore 32 bit Windows for now?

Mingw-w64 in Arch is very similar to msys2. They both use msvcrt.dll with is msvc but in combination with libgcc and mingw-w64 libraries.

Are you sure you used 32 bit on Arch?

**Comment by jschueller** [comment]
Absolutely positive.

I don't think archlinux toolchain doesn't use any native msvcrt.dll

As we are compiling from linux it's easier to avoid that unwanted native libs get linked.

**Comment by mingwandroid** [comment]
I can guarantee 100% that any and every mingw and mingw-w64 toolchain that has ever been produced uses msvcrt.dll (or very occasionally one of the more modern ones). There is simply no way to write user mode Windows software without using a MS provided CRT.

**Comment by jschueller** [comment]
@mingwandroid ok, I'm guessing the exception handling must occur in the gcc libs then.

**Comment by jschueller** [comment]
@mingwandroid do you know some mingw guru that could help us here ?

**Comment by mingwandroid** [comment]
I will try to find one with some time to look into this, but it won't be until mid-September at the earliest, sorry.

**Comment by jschueller** [comment]
hello @mingwandroid 
I hope you're not too mad from last time we discussed and that we can continue hacking on conda-forge :smiley:
I just wanted to ask if you still have in mind that m2w64/exceptions issue.

**Comment by mingwandroid** [comment]
Hey, not mad in the least! I need to rebuild all the R packages next; that shouldn't take *too* long but it you don't hear back from me in 2 weeks please ping me again.

**Comment by jschueller** [comment]
ok, cool

**Comment by jschueller** [comment]
hi @mingwandroid, ready to hack on m2w64 exceptions ?

**Comment by jschueller** [comment]
hi @mingwandroid, still on top of mingw stuff ?

**Comment by mingwandroid** [comment]
Sorry this keeps getting kicked down the road, pings are fine though to bring it back onto my radar.

**Comment by mingwandroid** [comment]
(and as usual I have a lot of work to do, though some of it to do with GCC on Windows for a change).

**Comment by jschueller** [comment]
@mingwandroid, since 32 bits is no longer an issue, I'm close to succeeding using your m2w64 toolchain here, many thanks for the help!

**Pull request closed without merging**
