### PR TITLE
Use m2w64

### PR DESCRIPTION
**Pull request by jschueller**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
@mingwandroid The current gcc (5.3) looks very slow to link (30min+) compared to what i'm used with 8.2 (~3-5min, but from linux) with some templates dependency enabled, is there a plan to update the toolchain ?

**Comment by jschueller** [comment]
My concern is also that I dont know wheter a module compiled with a more recent mingw toolchain will be binary-compatible with openturns in conda-forge. Your GCC version is 5.3 so I think the new c++11 abi should is used, I dont think there should be be other compatility issues, or ? Even if I link dinamically with a more recent crt or winptreads ?

**Comment by mingwandroid** [comment]
That's not how GCC works on Windows. The crt is different entirely from the normal msvc one. Also there's no ABI issues since we use one single compiler for everything at present.

What did you mean?

**Comment by jschueller** [comment]
I may use mingw/gcc 8.2.0 for another python module, will the binaries be compatible with the ones produced here with mingw/gcc 5.3 ? Also the mingw-crt/winpthreads is 6.0.0 instead of 5.0-git here.

**Comment by mingwandroid** [comment]
They don't need to be compatible provided the filenames are different.

**Pull request merged**
